
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Global/Header";
import SideNav from "@/components/SideNav/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="container box-border grid grid-cols-4 gap-4 bg-light-primary">
        <Header />

        <SideNav />

        <main className="grid grid-cols-3 col-span-3 gap-4 h-admin-full-card-height">
          {children}
        </main>

      </body>
    </html>
  );
}
